# fly.toml app configuration file generated for quiz-lib on 2025-09-02T01:38:47Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'quiz-lib'
primary_region = 'sin'

[build]
  # 使用根目录的 nixpacks.toml 配置

[env]
  PORT = "8000"
  PYTHONPATH = "/app"
  PYTHONDONTWRITEBYTECODE = "1"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  
  [[http_service.checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# 自动停止和启动配置
[experimental]
  auto_rollback = true

# Console 命令 (可选)
[console_command]
  command = "/bin/bash"
